# Generated by Django 5.2.9 on 2025-12-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='Flight_number',
            new_name='flight_number',
        ),
    ]
