# Generated by Django 5.2.9 on 2025-12-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_flight_number_flight_flight_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='flight_number',
            new_name='Flight_number',
        ),
    ]
